import type { GameDataIndex } from '../gamedata/index.js';

/**
 * Evolution candy costs PvPoke's game master does not carry. Keyed "from->to" on base (non-shadow)
 * ids. Anything not listed falls back to the family-length heuristic and is flagged estimated.
 */
const OVERRIDES: Record<string, number> = {
  'magikarp->gyarados': 400,
  'wailmer->wailord': 400,
  'swablu->altaria': 400,
  'noibat->noivern': 400,
  'meltan->melmetal': 400,
  'feebas->milotic': 100,
  'caterpie->metapod': 12,
  'metapod->butterfree': 50,
  'weedle->kakuna': 12,
  'kakuna->beedrill': 50,
  'pidgey->pidgeotto': 12,
  'pidgeotto->pidgeot': 50,
  'rattata->raticate': 25,
  'wurmple->silcoon': 12,
  'wurmple->cascoon': 12,
  'silcoon->beautifly': 50,
  'cascoon->dustox': 50,
  'zigzagoon->linoone': 25,
  'bidoof->bibarel': 50,
  'rookidee->corvisquire': 50,
  'corvisquire->corviknight': 100,
  'marill->azumarill': 25,
  'azurill->marill': 25,
  'meditite->medicham': 50,
  'wooper->quagsire': 50,
  'stunfisk->stunfisk': 0,
  'trapinch->vibrava': 25,
  'vibrava->flygon': 100,
  'mankey->primeape': 50,
  'primeape->annihilape': 100,
  'tinkatink->tinkatuff': 25,
  'tinkatuff->tinkaton': 100,
  'seel->dewgong': 50,
  'chinchou->lanturn': 50,
  'shellder->cloyster': 50,
  'skarmory->skarmory': 0,
  'lickitung->lickilicky': 100,
  'cubone->marowak': 50,
  'ralts->kirlia': 25,
  'kirlia->gardevoir': 100,
  'kirlia->gallade': 100,
  'deino->zweilous': 25,
  'zweilous->hydreigon': 100,
  'axew->fraxure': 25,
  'fraxure->haxorus': 100,
  'froakie->frogadier': 25,
  'frogadier->greninja': 100,
  'bulbasaur->ivysaur': 25,
  'ivysaur->venusaur': 100,
  'charmander->charmeleon': 25,
  'charmeleon->charizard': 100,
  'squirtle->wartortle': 25,
  'wartortle->blastoise': 100,
  'totodile->croconaw': 25,
  'croconaw->feraligatr': 100,
  'larvitar->pupitar': 25,
  'pupitar->tyranitar': 100,
  'bagon->shelgon': 25,
  'shelgon->salamence': 100,
  'beldum->metang': 25,
  'metang->metagross': 100,
  'gible->gabite': 25,
  'gabite->garchomp': 100,
  'dratini->dragonair': 25,
  'dragonair->dragonite': 100,
  'machop->machoke': 25,
  'machoke->machamp': 100,
  'abra->kadabra': 25,
  'kadabra->alakazam': 100,
  'gastly->haunter': 25,
  'haunter->gengar': 100,
  'fletchling->fletchinder': 25,
  'fletchinder->talonflame': 100,
  'sandshrew->sandslash': 50,
  'vulpix->ninetales': 50,
  'growlithe->arcanine': 50,
  'shroomish->breloom': 50,
  'stunky->skuntank': 50,
  'shelmet->accelgor': 50,
  'tangela->tangrowth': 100,
  'roselia->roserade': 100,
  'budew->roselia': 25,
  'dewpider->araquanid': 50,
  'skorupi->drapion': 50,
  'slakoth->vigoroth': 25,
  'vigoroth->slaking': 100,
  'poliwag->poliwhirl': 25,
  'poliwhirl->poliwrath': 100,
  'poliwhirl->politoed': 100,
  'eevee->vaporeon': 25,
  'eevee->jolteon': 25,
  'eevee->flareon': 25,
  'eevee->espeon': 25,
  'eevee->umbreon': 25,
  'eevee->leafeon': 25,
  'eevee->glaceon': 25,
  'eevee->sylveon': 25,
  'cottonee->whimsicott': 50,
  'hoppip->skiploom': 25,
  'skiploom->jumpluff': 100,
  'diglett->dugtrio': 50,
  'geodude->graveler': 25,
  'graveler->golem': 100,
  'onix->steelix': 50,
  'scyther->scizor': 50,
  'pinsir->pinsir': 0,
  'oddish->gloom': 25,
  'gloom->vileplume': 100,
  'gloom->bellossom': 100,
  'bellsprout->weepinbell': 25,
  'weepinbell->victreebel': 100,
  'nidoran_female->nidorina': 25,
  'nidorina->nidoqueen': 100,
  'nidoran_male->nidorino': 25,
  'nidorino->nidoking': 100,
  'clefairy->clefable': 50,
  'jigglypuff->wigglytuff': 50,
  'drowzee->hypno': 50,
  'koffing->weezing': 50,
  'swinub->piloswine': 25,
  'piloswine->mamoswine': 100,
  'teddiursa->ursaring': 25,
  'ursaring->ursaluna': 100,
  'houndour->houndoom': 50,
  'phanpy->donphan': 50,
  'larvesta->volcarona': 400,
  'pawniard->bisharp': 50,
  'bisharp->kingambit': 100,
  'mareep->flaaffy': 25,
  'flaaffy->ampharos': 100,
  'toxel->toxtricity': 50,
  'mudkip->marshtomp': 25,
  'marshtomp->swampert': 100,
  'torchic->combusken': 25,
  'combusken->blaziken': 100,
  'treecko->grovyle': 25,
  'grovyle->sceptile': 100,
  'chikorita->bayleef': 25,
  'bayleef->meganium': 100,
  'cyndaquil->quilava': 25,
  'quilava->typhlosion': 100,
  'fennekin->braixen': 25,
  'braixen->delphox': 100,
  'petilil->lilligant': 50,
  'tyrunt->tyrantrum': 50,
  'goomy->sliggoo': 25,
  'sliggoo->goodra': 100,
  'ferroseed->ferrothorn': 50,
  'golett->golurk': 50,
  'bronzor->bronzong': 50,
  'barboach->whiscash': 50,
  'clamperl->huntail': 50,
  'clamperl->gorebyss': 50,
  'spinarak->ariados': 50,
  'nosepass->probopass': 50,
  'lileep->cradily': 50,
  'anorith->armaldo': 50,
  'shieldon->bastiodon': 50,
  'cranidos->rampardos': 50,
  'drilbur->excadrill': 50,
  'timburr->gurdurr': 50,
  'gurdurr->conkeldurr': 200,
  'litwick->lampent': 25,
  'lampent->chandelure': 100,
  'yamask->cofagrigus': 50,
  'yamask->runerigus': 50,
  'frillish->jellicent': 50,
  'ducklett->swanna': 50,
  'sewaddle->swadloon': 25,
  'swadloon->leavanny': 100,
  'venipede->whirlipede': 25,
  'whirlipede->scolipede': 100,
  'lotad->lombre': 25,
  'lombre->ludicolo': 100,
  'seedot->nuzleaf': 25,
  'nuzleaf->shiftry': 100,
  'nincada->ninjask': 50,
  'nincada->shedinja': 50,
  'whismur->loudred': 12,
  'loudred->exploud': 50,
  'makuhita->hariyama': 50,
  'aron->lairon': 25,
  'lairon->aggron': 100,
  'electrike->manectric': 50,
  'gulpin->swalot': 50,
  'carvanha->sharpedo': 50,
  'numel->camerupt': 50,
  'spoink->grumpig': 50,
  'swablu->altaria_shadow': 400,
  'snorunt->glalie': 50,
  'snorunt->froslass': 50,
  'spheal->sealeo': 25,
  'sealeo->walrein': 100,
  'duskull->dusclops': 25,
  'dusclops->dusknoir': 100,
  'shuppet->banette': 50,
  'wynaut->wobbuffet': 25,
  'togepi->togetic': 25,
  'togetic->togekiss': 100,
  'pichu->pikachu': 25,
  'pikachu->raichu': 50,
  'sandile->krokorok': 25,
  'krokorok->krookodile': 100,
  'scraggy->scrafty': 50,
  'vullaby->mandibuzz': 50,
  'rufflet->braviary': 50,
  'joltik->galvantula': 50,
  'tympole->palpitoad': 25,
  'palpitoad->seismitoad': 100,
  'karrablast->escavalier': 200,
  'foongus->amoonguss': 50,
  'trubbish->garbodor': 50,
  'minccino->cinccino': 50,
  'dwebble->crustle': 50,
  'darumaka->darmanitan_standard': 50,
  'pancham->pangoro': 50,
  'skrelp->dragalge': 50,
  'clauncher->clawitzer': 50,
  'honedge->doublade': 25,
  'doublade->aegislash_shield': 100,
  'phantump->trevenant': 200,
  'pumpkaboo_average->gourgeist_average': 200,
  'bergmite->avalugg': 50,
  'espurr->meowstic': 50,
  'spritzee->aromatisse': 50,
  'swirlix->slurpuff': 50,
  'inkay->malamar': 50,
  'binacle->barbaracle': 50,
  'helioptile->heliolisk': 50,
  'grubbin->charjabug': 25,
  'charjabug->vikavolt': 100,
  'mudbray->mudsdale': 50,
  'stufful->bewear': 50,
  'wimpod->golisopod': 400,
  'sandygast->palossand': 50,
  'jangmo_o->hakamo_o': 25,
  'hakamo_o->kommo_o': 100,
  'rockruff->lycanroc_midday': 50,
  'crabrawler->crabominable': 50,
  'wooloo->dubwool': 50,
  'chewtle->drednaw': 50,
  'yamper->boltund': 50,
  'rolycoly->carkol': 25,
  'carkol->coalossal': 100,
  'applin->flapple': 200,
  'applin->appletun': 200,
  'silicobra->sandaconda': 50,
  'arrokuda->barraskewda': 50,
  'hatenna->hattrem': 25,
  'hattrem->hatterene': 100,
  'impidimp->morgrem': 25,
  'morgrem->grimmsnarl': 100,
  'sinistea->polteageist': 50,
  'milcery->alcremie': 400,
  'snom->frosmoth': 400,
  'cufant->copperajah': 50,
  'dreepy->drakloak': 25,
  'drakloak->dragapult': 100,
  'lechonk->oinkologne': 50,
  'pawmi->pawmo': 25,
  'pawmo->pawmot': 100,
  'nymble->lokix': 50,
  'shroodle->grafaiai': 50,
  'wattrel->kilowattrel': 50,
  'greavard->houndstone': 50,
  'bramblin->brambleghast': 50,
  'flittle->espathra': 50,
  'wiglett->wugtrio': 50,
  'finizen->palafin_zero': 50,
  'glimmet->glimmora': 50,
  'frigibax->arctibax': 25,
  'arctibax->baxcalibur': 100,
  'poltchageist->sinistcha': 50,
};

export function evolutionCandy(
  fromId: string,
  toId: string,
  index: GameDataIndex,
): { candy: number; estimated: boolean } {
  const from = index.baseOf(fromId);
  const to = index.baseOf(toId);
  if (from === to) {
    return { candy: 0, estimated: false };
  }
  const exact = OVERRIDES[`${from}->${to}`];
  if (exact !== undefined) {
    return { candy: exact, estimated: false };
  }
  const chain = index.familyChainLength(from);
  const depth = index.stageDepth(to);
  if (chain <= 2) {
    return { candy: 50, estimated: true };
  }
  return { candy: depth <= 1 ? 25 : 100, estimated: true };
}

/** Total candy to evolve from one stage to a later stage along the family chain. */
export function evolutionCandyPath(
  fromId: string,
  toId: string,
  index: GameDataIndex,
): { candy: number; estimated: boolean; steps: string[] } {
  const path: string[] = [];
  let candy = 0;
  let estimated = false;
  const from = index.baseOf(fromId);
  const to = index.baseOf(toId);
  if (from === to) {
    return { candy: 0, estimated: false, steps: [] };
  }
  // Walk down from `to` via parents until we hit `from`.
  const chain: string[] = [to];
  let cur = index.species(to);
  const guard = new Set<string>();
  while (cur && cur.parentId && cur.parentId !== from && !guard.has(cur.speciesId)) {
    guard.add(cur.speciesId);
    chain.unshift(cur.parentId);
    cur = index.species(cur.parentId);
  }
  if (!cur || cur.parentId !== from) {
    return { candy: 0, estimated: true, steps: [] };
  }
  let prev = from;
  for (const stage of chain) {
    const c = evolutionCandy(prev, stage, index);
    candy += c.candy;
    estimated = estimated || c.estimated;
    path.push(`${prev}->${stage}`);
    prev = stage;
  }
  return { candy, estimated, steps: path };
}
