/** Poke Genie "Form" column value -> PvPoke speciesId suffix. Blank and Normal carry no suffix. */
export const FORM_SUFFIX: Record<string, string> = {
  '': '',
  Normal: '',
  Mega: '_mega',
  'Mega X': '_mega_x',
  'Mega Y': '_mega_y',
  Galar: '_galarian',
  Galarian: '_galarian',
  Alola: '_alolan',
  Alolan: '_alolan',
  Hisui: '_hisuian',
  Hisuian: '_hisuian',
  Paldea: '_paldean',
  Paldean: '_paldean',
  Armored: '_armored',
  Origin: '_origin',
  Altered: '_altered',
  Incarnate: '_incarnate',
  Therian: '_therian',
  Small: '_small',
  Average: '_average',
  Large: '_large',
  Super: '_super',
  Male: '_male',
  Female: '_female',
  Hero: '_hero',
  Zero: '_zero',
  '10%': '_10',
  '50%': '',
  Complete: '_complete',
  Attack: '_attack',
  Defense: '_defense',
  Speed: '_speed',
  Sunny: '_sunny',
  Rainy: '_rainy',
  Snowy: '_snowy',
  Plant: '_plant',
  Sandy: '_sandy',
  Trash: '_trash',
  Overcast: '_overcast',
  Sunshine: '_sunshine',
  Heat: '_heat',
  Wash: '_wash',
  Frost: '_frost',
  Fan: '_fan',
  Mow: '_mow',
  Sky: '_sky',
  Land: '_land',
  Standard: '_standard',
  Zen: '_zen',
  Aria: '_aria',
  Pirouette: '_pirouette',
  Ordinary: '_ordinary',
  Resolute: '_resolute',
  Black: '_black',
  White: '_white',
  Shield: '_shield',
  Blade: '_blade',
  Midday: '_midday',
  Midnight: '_midnight',
  Dusk: '_dusk',
  Solo: '_solo',
  School: '_school',
  Baile: '_baile',
  'Pom-Pom': '_pompom',
  "Pa'u": '_pau',
  Sensu: '_sensu',
  Dawn: '_dawn',
  Ultra: '_ultra',
  Crowned: '_crowned',
  Ice: '_ice',
  Noice: '_noice',
  'Full Belly': '_full_belly',
  Hangry: '_hangry',
  Single: '_single_strike',
  'Single Strike': '_single_strike',
  Rapid: '_rapid_strike',
  'Rapid Strike': '_rapid_strike',
  Curly: '_curly',
  Droopy: '_droopy',
  Stretchy: '_stretchy',
  Two: '_two_segment',
  Three: '_three_segment',
  Family: '_family_of_four',
  'Family of Four': '_family_of_four',
  'Family of Three': '_family_of_three',
  Bloodmoon: '_bloodmoon',
  Green: '_green',
  Plumage: '_green',
};

/** Forms that map to a base species for open Great League play (the player owns the base). */
export const FORMS_TO_BASE = new Set(['Mega', 'Mega X', 'Mega Y']);

export interface Override {
  /** slug of the Poke Genie name */
  name: string;
  /** exact Form value, or '*' for any */
  form: string;
  speciesId: string | null;
  reason?: 'unsupported-form';
}

/** Cases the slug + suffix rule cannot produce. Checked before the generic rule. */
export const OVERRIDES: Override[] = [
  { name: 'thundurus', form: 'Normal', speciesId: 'thundurus_incarnate' },
  { name: 'thundurus', form: '', speciesId: 'thundurus_incarnate' },
  { name: 'tornadus', form: 'Normal', speciesId: 'tornadus_incarnate' },
  { name: 'tornadus', form: '', speciesId: 'tornadus_incarnate' },
  { name: 'landorus', form: 'Normal', speciesId: 'landorus_incarnate' },
  { name: 'landorus', form: '', speciesId: 'landorus_incarnate' },
  { name: 'enamorus', form: 'Normal', speciesId: 'enamorus_incarnate' },
  { name: 'enamorus', form: '', speciesId: 'enamorus_incarnate' },
  { name: 'tatsugiri', form: '*', speciesId: 'tatsugiri_curly' },
  { name: 'morpeko', form: '*', speciesId: 'morpeko_full_belly' },
  { name: 'gimmighoul', form: 'Roaming', speciesId: null, reason: 'unsupported-form' },
  { name: 'giratina', form: '', speciesId: 'giratina_altered' },
  { name: 'giratina', form: 'Normal', speciesId: 'giratina_altered' },
  { name: 'deoxys', form: 'Normal', speciesId: 'deoxys' },
  { name: 'shaymin', form: 'Land', speciesId: 'shaymin_land' },
  { name: 'shaymin', form: '', speciesId: 'shaymin_land' },
  { name: 'meowstic', form: 'Male', speciesId: 'meowstic' },
  { name: 'oricorio', form: 'Baile', speciesId: 'oricorio_baile' },
  { name: 'zygarde', form: '50%', speciesId: 'zygarde' },
  { name: 'zygarde', form: '', speciesId: 'zygarde' },
  { name: 'darmanitan', form: '', speciesId: 'darmanitan_standard' },
  { name: 'darmanitan', form: 'Standard', speciesId: 'darmanitan_standard' },
  { name: 'darmanitan', form: 'Galar', speciesId: 'darmanitan_galarian_standard' },
  { name: 'wormadam', form: 'Plant', speciesId: 'wormadam_plant' },
  { name: 'burmy', form: 'Plant', speciesId: 'burmy_plant' },
  { name: 'nidoran♀', form: '*', speciesId: 'nidoran_female' },
  { name: 'nidoran♂', form: '*', speciesId: 'nidoran_male' },
  { name: 'nidoran_f', form: '*', speciesId: 'nidoran_female' },
  { name: 'nidoran_m', form: '*', speciesId: 'nidoran_male' },
  { name: 'mr_mime', form: '', speciesId: 'mr_mime' },
  { name: 'mr_mime', form: 'Galar', speciesId: 'mr_mime_galarian' },
  { name: 'mime_jr', form: '*', speciesId: 'mime_jr' },
  { name: 'ho_oh', form: '*', speciesId: 'ho_oh' },
  { name: 'porygon_z', form: '*', speciesId: 'porygon_z' },
  { name: 'jangmo_o', form: '*', speciesId: 'jangmo_o' },
  { name: 'hakamo_o', form: '*', speciesId: 'hakamo_o' },
  { name: 'kommo_o', form: '*', speciesId: 'kommo_o' },
  { name: 'type_null', form: '*', speciesId: 'type_null' },
  { name: 'tapu_koko', form: '*', speciesId: 'tapu_koko' },
  { name: 'tapu_lele', form: '*', speciesId: 'tapu_lele' },
  { name: 'tapu_bulu', form: '*', speciesId: 'tapu_bulu' },
  { name: 'tapu_fini', form: '*', speciesId: 'tapu_fini' },
  { name: 'sirfetchd', form: '*', speciesId: 'sirfetchd' },
  { name: 'farfetchd', form: '', speciesId: 'farfetchd' },
  { name: 'farfetchd', form: 'Galar', speciesId: 'farfetchd_galarian' },
  { name: 'flabebe', form: '*', speciesId: 'flabebe' },
  { name: 'urshifu', form: 'Single Strike', speciesId: 'urshifu_single_strike' },
  { name: 'urshifu', form: 'Rapid Strike', speciesId: 'urshifu_rapid_strike' },
  { name: 'indeedee', form: 'Male', speciesId: 'indeedee_male' },
  { name: 'indeedee', form: '', speciesId: 'indeedee_male' },
  { name: 'basculin', form: '', speciesId: 'basculin' },
  { name: 'basculin', form: 'Red Striped', speciesId: 'basculin' },
  { name: 'basculin', form: 'Blue Striped', speciesId: 'basculin' },
  { name: 'basculin', form: 'White Striped', speciesId: 'basculin_white_striped' },
  { name: 'toxtricity', form: '', speciesId: 'toxtricity' },
  { name: 'toxtricity', form: 'Amped', speciesId: 'toxtricity' },
  { name: 'toxtricity', form: 'Low Key', speciesId: 'toxtricity_low_key' },
  { name: 'eiscue', form: '', speciesId: 'eiscue_ice' },
  { name: 'pumpkaboo', form: '', speciesId: 'pumpkaboo_average' },
  { name: 'gourgeist', form: '', speciesId: 'gourgeist_average' },
  { name: 'lycanroc', form: '', speciesId: 'lycanroc_midday' },
  { name: 'wishiwashi', form: '', speciesId: 'wishiwashi_solo' },
  { name: 'palafin', form: '', speciesId: 'palafin_zero' },
  { name: 'dudunsparce', form: '*', speciesId: 'dudunsparce' },
  { name: 'maushold', form: '*', speciesId: 'maushold' },
  { name: 'squawkabilly', form: '*', speciesId: 'squawkabilly' },
  { name: 'ogerpon', form: '', speciesId: 'ogerpon' },
];
