import type { AchievementTier } from './types.js';

export interface KantoEntry {
  /** PvPoke species id (also the sprite file name). */
  id: string;
  dex: number;
  tier: AchievementTier;
}

/**
 * Kanto's 151 in dex order with the tier each one is drawn in. Hand kept: move an entry to change
 * how rare a Pokemon is. Mewtwo and Mew are top and only top achievements draw them.
 */
const TABLE: readonly [string, AchievementTier][] = [
  ['bulbasaur', 'easy'],
  ['ivysaur', 'mid'],
  ['venusaur', 'hard'],
  ['charmander', 'easy'],
  ['charmeleon', 'mid'],
  ['charizard', 'hard'],
  ['squirtle', 'easy'],
  ['wartortle', 'mid'],
  ['blastoise', 'hard'],
  ['caterpie', 'easy'],
  ['metapod', 'mid'],
  ['butterfree', 'hard'],
  ['weedle', 'easy'],
  ['kakuna', 'mid'],
  ['beedrill', 'hard'],
  ['pidgey', 'easy'],
  ['pidgeotto', 'mid'],
  ['pidgeot', 'hard'],
  ['rattata', 'easy'],
  ['raticate', 'mid'],
  ['spearow', 'easy'],
  ['fearow', 'mid'],
  ['ekans', 'easy'],
  ['arbok', 'mid'],
  ['pikachu', 'easy'],
  ['raichu', 'mid'],
  ['sandshrew', 'easy'],
  ['sandslash', 'mid'],
  ['nidoran_female', 'easy'],
  ['nidorina', 'mid'],
  ['nidoqueen', 'hard'],
  ['nidoran_male', 'easy'],
  ['nidorino', 'mid'],
  ['nidoking', 'hard'],
  ['clefairy', 'easy'],
  ['clefable', 'mid'],
  ['vulpix', 'easy'],
  ['ninetales', 'mid'],
  ['jigglypuff', 'easy'],
  ['wigglytuff', 'mid'],
  ['zubat', 'easy'],
  ['golbat', 'mid'],
  ['oddish', 'easy'],
  ['gloom', 'mid'],
  ['vileplume', 'hard'],
  ['paras', 'easy'],
  ['parasect', 'mid'],
  ['venonat', 'easy'],
  ['venomoth', 'mid'],
  ['diglett', 'easy'],
  ['dugtrio', 'mid'],
  ['meowth', 'easy'],
  ['persian', 'mid'],
  ['psyduck', 'easy'],
  ['golduck', 'mid'],
  ['mankey', 'easy'],
  ['primeape', 'mid'],
  ['growlithe', 'easy'],
  ['arcanine', 'mid'],
  ['poliwag', 'easy'],
  ['poliwhirl', 'mid'],
  ['poliwrath', 'hard'],
  ['abra', 'easy'],
  ['kadabra', 'mid'],
  ['alakazam', 'hard'],
  ['machop', 'easy'],
  ['machoke', 'mid'],
  ['machamp', 'hard'],
  ['bellsprout', 'easy'],
  ['weepinbell', 'mid'],
  ['victreebel', 'hard'],
  ['tentacool', 'easy'],
  ['tentacruel', 'mid'],
  ['geodude', 'easy'],
  ['graveler', 'mid'],
  ['golem', 'hard'],
  ['ponyta', 'easy'],
  ['rapidash', 'mid'],
  ['slowpoke', 'easy'],
  ['slowbro', 'mid'],
  ['magnemite', 'easy'],
  ['magneton', 'mid'],
  ['farfetchd', 'hard'],
  ['doduo', 'easy'],
  ['dodrio', 'mid'],
  ['seel', 'easy'],
  ['dewgong', 'mid'],
  ['grimer', 'easy'],
  ['muk', 'mid'],
  ['shellder', 'easy'],
  ['cloyster', 'mid'],
  ['gastly', 'easy'],
  ['haunter', 'mid'],
  ['gengar', 'hard'],
  ['onix', 'hard'],
  ['drowzee', 'easy'],
  ['hypno', 'mid'],
  ['krabby', 'easy'],
  ['kingler', 'mid'],
  ['voltorb', 'easy'],
  ['electrode', 'mid'],
  ['exeggcute', 'easy'],
  ['exeggutor', 'mid'],
  ['cubone', 'easy'],
  ['marowak', 'mid'],
  ['hitmonlee', 'hard'],
  ['hitmonchan', 'hard'],
  ['lickitung', 'hard'],
  ['koffing', 'easy'],
  ['weezing', 'mid'],
  ['rhyhorn', 'easy'],
  ['rhydon', 'mid'],
  ['chansey', 'hard'],
  ['tangela', 'hard'],
  ['kangaskhan', 'hard'],
  ['horsea', 'easy'],
  ['seadra', 'mid'],
  ['goldeen', 'easy'],
  ['seaking', 'mid'],
  ['staryu', 'easy'],
  ['starmie', 'mid'],
  ['mr_mime', 'hard'],
  ['scyther', 'hard'],
  ['jynx', 'hard'],
  ['electabuzz', 'hard'],
  ['magmar', 'hard'],
  ['pinsir', 'hard'],
  ['tauros', 'hard'],
  ['magikarp', 'easy'],
  ['gyarados', 'hard'],
  ['lapras', 'hard'],
  ['ditto', 'hard'],
  ['eevee', 'easy'],
  ['vaporeon', 'hard'],
  ['jolteon', 'hard'],
  ['flareon', 'hard'],
  ['porygon', 'hard'],
  ['omanyte', 'easy'],
  ['omastar', 'mid'],
  ['kabuto', 'easy'],
  ['kabutops', 'mid'],
  ['aerodactyl', 'hard'],
  ['snorlax', 'hard'],
  ['articuno', 'elite'],
  ['zapdos', 'elite'],
  ['moltres', 'elite'],
  ['dratini', 'easy'],
  ['dragonair', 'mid'],
  ['dragonite', 'hard'],
  ['mewtwo', 'top'],
  ['mew', 'top'],
];

export const KANTO: readonly KantoEntry[] = TABLE.map(([id, tier], i) => ({
  id,
  dex: i + 1,
  tier,
}));

export const KANTO_IDS: ReadonlySet<string> = new Set(KANTO.map((k) => k.id));
